version: "3"
services:
  backend_game:
    build: ./backend
    command: ["./game/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend/game:/code/game
    env_file:
      - ./env/backend_game.env
    ports:
      - "8000:8000"

  backend_chat:
    build: ./backend
    command: ["uvicorn", "chat.main:app", "--host", "0.0.0.0", "--port", "4000"]
    volumes:
      - ./backend/chat:/code/chat
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    volumes:
    - /app/node_modules
    - ./frontend:/app
    environment:
    - HOST=0.0.0.0
    ports:
    - "3000:3000"

  postgres:
    image: postgres:11.6-alpine
    volumes:
      - ./pg_data_dev:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    volumes:
    - data:/data/db
    env_file:
      - ./env/mongo.env

volumes:
  data:
