# Generated by Django 3.1.4 on 2020-12-28 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201228_0522'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
