# Generated by Django 3.1.4 on 2021-01-02 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_auto_20210101_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_creator',
        ),
        migrations.AddField(
            model_name='game',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_game_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
